### ISSUE TITLE
Wire.requestFrom() should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [Danny24/smart_motor_driver#1]
The `Wire.endTransmission()` should only be used when writing data.

In the file "smart_motor_driver/Software/testing/i2c_smart_motor_tester/i2c_smart_motor_tester.ino", the `Wire.endTransmission()` after a `Wire.requestFrom()` can be removed. They are at the moment at line 45 and 55.

Explanation: [Common-mistakes#2](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#2)

**Comment by Danny24** [comment]
Thanks, these lines (45 and 55) will be removed in the next release.
